name: Update README 2

on: 
  schedule:
    # Se ejecuta en el minuto 0, cada 12 horas
    - cron: "0 */12 * * *"
  # Permite ejecutar el flujo de trabajo manualmente desde la pestaña "Actions"
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README
    
    # Fundamental: Otorga permisos para hacer el commit en tu repositorio
    permissions:
      contents: write

    steps:
      # Actualizado a v4 para evitar errores de Node.js
      - uses: actions/checkout@v4

      - uses: Readme-Workflows/recent-activity@v2.4.1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}